name: API Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Inso.
        uses: kong/setup-inso@v1
        with:
          inso-version: 2.4.0

      - name: Setup Node.
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install concurrently and wait-on
        run: npm i -g wait-on concurrently

      - name: Git checkout
        uses: actions/checkout@v2

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 6

      - name: Concurrently run server and tests
        run: concurrently -k "make inso-ci" "make run"
